# Generated by Django 2.2.13 on 2020-06-26 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_news_keyword_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
