# Generated by Django 2.2.13 on 2020-06-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_news_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='headline',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
