# Generated by Django 2.2.13 on 2020-06-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_newshistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
