# Generated by Django 2.2.13 on 2020-06-27 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='source',
        ),
        migrations.AddField(
            model_name='news',
            name='source_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Sources'),
            preserve_default=False,
        ),
    ]
